import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const deckDir = path.dirname(fileURLToPath(import.meta.url));
const modules = [
  { key: 'setup', label: '01 API·환경' },
  { key: 'ui', label: '02 화면 만들기' },
  { key: 'data', label: '03 DART·AI' },
  { key: 'deploy', label: '04 배포' },
];

const css = String.raw`
  :root{--bg:#fff;--ink:#0b1736;--muted:#596579;--line:#c7d2e5;--soft:#eaf0fb;--blue:#123fc2;--navy:#071526;--green:#07825e;--red:#c73737}
  *{box-sizing:border-box}html,body{margin:0;padding:0}body{width:720pt;height:405pt;overflow:hidden;background:var(--bg);color:var(--ink);font-family:'Pretendard','Noto Sans KR','Malgun Gothic',sans-serif;padding:20pt 34pt 22pt;position:relative;display:flex;flex-direction:column;word-break:keep-all;text-wrap:pretty}body.dark{background:var(--navy);color:#fff}h1,h2,h3,p,ul,ol,pre{margin:0}h1,h2,h3,p,li{padding-bottom:2px}code{font-family:'Cascadia Code','D2Coding',Consolas,monospace}
  .rail{height:19pt;display:grid;grid-template-columns:repeat(4,1fr) 40pt;gap:10pt;border-bottom:1pt solid var(--line)}.rail p{font-size:9.5pt;line-height:1;color:var(--muted);padding-bottom:6pt}.rail .active{color:var(--blue);font-weight:800;border-bottom:2pt solid var(--blue)}.rail .page{text-align:right}.title{margin-top:15pt}.kicker{color:var(--blue);font-size:10pt;font-weight:800;letter-spacing:.04em;margin-bottom:6pt}.title h1{font-size:26pt;line-height:1.26;letter-spacing:-.035em;font-weight:790;text-wrap:balance}.subtitle{margin-top:7pt;color:var(--muted);font-size:14.5pt;line-height:1.42;max-width:620pt}
  .content{margin-top:13pt;flex:1;min-height:0}.split{height:100%;display:grid;grid-template-columns:1fr 1fr;gap:24pt;min-height:0}.split-40{height:100%;display:grid;grid-template-columns:40% 60%;gap:22pt;min-height:0}.split-60{height:100%;display:grid;grid-template-columns:60% 40%;gap:22pt;min-height:0}.split>*,.split-40>*,.split-60>*{min-height:0;min-width:0}.vcenter{display:flex;flex-direction:column;justify-content:center}.center{display:flex;align-items:center;justify-content:center}.body{font-size:15pt;line-height:1.48}.small{font-size:13.5pt;line-height:1.4;color:var(--muted)}.strong{font-weight:800}.accent{color:var(--blue)}
  .code{height:100%;background:var(--navy);border-radius:10pt;padding:16pt 18pt;color:#fff;display:flex;flex-direction:column;justify-content:center;overflow:hidden}.code .bar{display:flex;gap:5pt;margin-bottom:12pt}.dot{width:7pt;height:7pt;border-radius:50%;background:#5e6b7f}.dot:nth-child(1){background:#f06c62}.dot:nth-child(2){background:#e9b949}.dot:nth-child(3){background:#4dbe87}.code pre{font-size:12.6pt;line-height:1.5;white-space:pre-wrap;word-break:break-word}.code.compact pre{font-size:9.8pt;line-height:1.26}.code .dim{color:#9eacc2}.code .ok{color:#72dda9}.code .warn{color:#ffd27a}.code .cursor{display:inline-block;width:7pt;height:13pt;background:#fff;vertical-align:-2pt}
  .prompt{height:100%;border:1.5pt solid var(--blue);border-radius:10pt;display:grid;grid-template-rows:auto 1fr auto;overflow:hidden;background:#fff}.prompt-head{background:var(--blue);color:#fff;padding:9pt 14pt;display:flex;justify-content:space-between;align-items:center}.prompt-head strong{font-size:12pt}.prompt-head span{font-size:9.5pt;opacity:.85}.prompt-text{padding:13pt 16pt;font-size:13pt;line-height:1.45;white-space:pre-wrap;overflow:hidden}.prompt.compact .prompt-text{padding:9pt 16pt;font-size:9.8pt;line-height:1.24}.prompt-foot{border-top:1pt solid var(--line);padding:7pt 14pt;color:var(--muted);font-size:10.5pt}
  .step{display:grid;grid-template-columns:36pt 1fr;gap:13pt;padding:7pt 0;border-bottom:1pt solid var(--line)}.step:last-child{border-bottom:0}.step .n{font-size:20pt;font-weight:850;color:var(--blue)}.step h3{font-size:15pt;line-height:1.3;margin-bottom:3pt}.step p{font-size:13.5pt;line-height:1.38;color:var(--muted)}.card{border-top:3pt solid var(--blue);background:var(--soft);padding:12pt 13pt;min-height:74pt}.card h3{font-size:15pt;margin-bottom:6pt}.card p{font-size:13.5pt;line-height:1.4;color:var(--muted)}.cards2{display:grid;grid-template-columns:1fr 1fr;gap:14pt}.cards3{display:grid;grid-template-columns:repeat(3,1fr);gap:12pt}.cards4{display:grid;grid-template-columns:repeat(4,1fr);gap:10pt}
  .flow{display:flex;align-items:center;gap:7pt}.node{flex:1;background:var(--soft);border-top:3pt solid var(--blue);padding:11pt 8pt;min-height:70pt;display:flex;flex-direction:column;justify-content:center}.node strong{font-size:14pt;margin-bottom:4pt}.node span{font-size:12pt;line-height:1.32;color:var(--muted)}.arrow{color:var(--blue);font-size:22pt;font-weight:800}
  .editor{height:100%;border:1pt solid #27364d;border-radius:9pt;overflow:hidden;background:#0b1220;color:#dbe6f8;display:grid;grid-template-rows:27pt 1fr}.editor-top{background:#182235;padding:6pt 12pt;font-size:10pt;color:#aebbd0}.editor-body{display:grid;grid-template-columns:122pt 1fr;min-height:0}.files{border-right:1pt solid #27364d;padding:10pt 9pt;font-size:10.5pt;line-height:1.62;color:#aebbd0}.files .on{color:#fff;font-weight:750}.source{padding:13pt 15pt;font-family:'Cascadia Code','D2Coding',Consolas,monospace;font-size:12.5pt;line-height:1.58;white-space:pre-wrap}.source .key{color:#79c0ff}.source .value{color:#a5d6ff}.source .comment{color:#7d899b}
  .browser{height:100%;border:1pt solid var(--line);border-radius:9pt;overflow:hidden;background:#fff;display:grid;grid-template-rows:29pt 1fr}.browser-top{background:#eef2f7;padding:6pt 10pt;font-size:10pt;color:#536176}.browser-body{padding:14pt 16pt;overflow:hidden}.sitebar{display:flex;align-items:center;justify-content:space-between;border-bottom:2pt solid #12539a;padding-bottom:8pt}.sitebar strong{font-size:15pt;color:#12539a}.menu{font-size:10pt;color:#506078}.mock-form{margin-top:13pt;border:1pt solid var(--line)}.mock-row{display:grid;grid-template-columns:112pt 1fr;border-bottom:1pt solid var(--line);min-height:28pt}.mock-row:last-child{border-bottom:0}.mock-row b{background:#f3f6fa;padding:7pt 9pt;font-size:11pt}.mock-row span{padding:7pt 10pt;font-size:11pt;color:#596579}.mock-button{display:inline-block;margin-top:11pt;background:#12539a;color:#fff;border-radius:3pt;padding:7pt 15pt;font-size:11pt;font-weight:750}
  .screen{height:calc(100% - 18pt);min-height:0;border:1pt solid var(--line);border-radius:9pt;overflow:hidden;background:#fff}.screen img{width:100%;height:100%;object-fit:contain;display:block}.caption{font-size:10.5pt;color:var(--muted);margin-top:5pt}.check{padding:7pt 0;border-bottom:1pt solid var(--line)}.check:last-child{border-bottom:0}.check strong{display:block;font-size:14pt;margin-bottom:3pt}.check span{font-size:12.5pt;color:var(--muted);line-height:1.36}.pass{color:var(--green)!important}.stop{color:var(--red)!important}
  table{width:100%;border-collapse:collapse;table-layout:fixed}th,td{text-align:left;vertical-align:top;padding:7pt 8pt;border-bottom:1pt solid var(--line)}th{background:var(--soft);color:var(--blue);font-size:12pt}td{font-size:12.5pt;line-height:1.35}.section-no{font-size:11pt;color:#afc4ff;letter-spacing:.08em;font-weight:800}.section-title{font-size:45pt;line-height:1.14;font-weight:520;letter-spacing:-.055em;margin-top:35pt;max-width:620pt}.section-sub{font-size:16pt;line-height:1.5;color:#c7d2e5;margin-top:18pt;max-width:590pt}.section-line{position:absolute;left:34pt;right:34pt;bottom:30pt;height:2pt;background:var(--blue)}
  .title h1,.section-title,.cover-title,.big{padding-bottom:9px}.cover-eyebrow{font-size:11pt;color:#afc4ff;letter-spacing:.08em;font-weight:800}.cover-title{font-size:49pt;line-height:1.12;font-weight:520;letter-spacing:-.06em;margin-top:16pt;max-width:630pt;padding-bottom:12px}.cover-sub{font-size:16pt;color:#c7d2e5;margin-top:18pt}.cover-meta{position:absolute;left:34pt;bottom:27pt;font-size:13pt;color:#afc4ff}.source-note{position:absolute;left:34pt;bottom:8pt;font-size:8.5pt;color:#768399}.big{font-size:42pt;line-height:1.12;font-weight:820;letter-spacing:-.05em}.rule{height:1pt;background:var(--line);margin:12pt 0}
`;

function rail(active, no){return `<div class="rail">${modules.map(m=>`<p class="${m.key===active?'active':''}">${m.label}</p>`).join('')}<p class="page">${String(no).padStart(2,'0')}</p></div>`}
let renderedPageNo=0;
function page({no,active='setup',kicker='',title='',subtitle='',content='',dark=false,source=''}){const actualNo=++renderedPageNo;return `<!doctype html><html lang="ko"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><style>${css}</style></head><body class="${dark?'dark':''}" data-module="${active}">${dark?'':rail(active,actualNo)}${title?`<div class="title">${kicker?`<p class="kicker">${kicker}</p>`:''}<h1>${title}</h1>${subtitle?`<p class="subtitle">${subtitle}</p>`:''}</div>`:''}${content}${source?`<p class="source-note">${source}</p>`:''}</body></html>`}
function section(no,moduleNo,title,sub){const active={"01":"setup","02":"ui","03":"data","04":"deploy"}[moduleNo]||'setup';return page({no,active,dark:true,content:`<p class="section-no">MODULE ${moduleNo}</p><h1 class="section-title">${title}</h1><p class="section-sub">${sub}</p><div class="section-line"></div>`})}
function code(lines,compact=false){return `<div class="code${compact?' compact':''}"><div class="bar"><i class="dot"></i><i class="dot"></i><i class="dot"></i></div><pre>${lines}</pre></div>`}
function prompt(label,text,foot='붙여넣기 → 제안 파일 확인 → 승인 → 검증',compact=false){return `<div class="prompt${compact?' compact':''}"><div class="prompt-head"><strong>${label}</strong><span>CLAUDE CODE</span></div><div class="prompt-text">${text}</div><div class="prompt-foot">${foot}</div></div>`}
function browserForm(rows,button='등록'){return `<div class="browser"><div class="browser-top">🔒 opendart.fss.or.kr</div><div class="browser-body"><div class="sitebar"><strong>OPEN DART</strong><span class="menu">오픈API 소개　 인증키 신청/관리　 개발가이드</span></div><div class="mock-form">${rows.map(([k,v])=>`<div class="mock-row"><b>${k}</b><span>${v}</span></div>`).join('')}</div>${button?`<span class="mock-button">${button}</span>`:''}</div></div>`}

const P={
  analyze:`이 저장소를 먼저 분석해줘. 아직 코드는 수정하지 마.\n\n1. 실행 진입점\n2. 화면 파일\n3. OpenDART 호출 위치\n4. 지표 계산 위치\n5. Vercel 배포 파일\n\n각 파일의 역할과 다음에 수정할 순서를 설명해줘.`,
  uiPlan:`HR Analytics 기본 화면을 만들려고 해.\n아직 수정하지 말고 계획만 작성해줘.\n\n필수 요소: 기업 검색, 선택 기업 2개, 기준연도,\n보고서 종류, 비교 버튼, 결과 영역.\n\n변경 파일·구현 순서·완료 기준을 표로 보여줘.`,
  uiShell:`계획의 첫 단계만 구현해줘.\n\nstatic/index.html과 static/styles.css에\n- 서비스 제목과 한 줄 소개\n- 기업 검색 입력창\n- 선택 기업 영역\n- 결과가 아직 없다는 안내\n를 만들어줘. 실제 API와 선택 동작은 아직 넣지 마.`,
  addSelection:`방금 만든 화면에 기업 선택 동작을 추가해줘.\n\n- 검색 결과를 임시 샘플 3개로 보여준다.\n- 최대 2개를 추가·삭제할 수 있다.\n- 중복 선택을 막는다.\n- 선택 수를 0/2처럼 표시한다.\n\n기존 화면 스타일과 파일 구조를 유지해줘.`,
  addPeriod:`기업 선택 기능은 그대로 두고 다음 기능만 추가해줘.\n\n- 기준연도 선택\n- 사업·반기·분기보고서 선택\n- 인력·보상 비교 버튼\n- 조건이 바뀌면 이전 결과 비우기\n\n아직 OpenDART와 AI는 호출하지 마.`,
  fix:`현재 화면과 터미널 오류를 읽어줘.\n원인 후보를 3개 이내로 좁힌 뒤 가장 작은 수정부터 적용해줘.\n수정 전 재현 조건, 수정 파일, 수정 후 확인 결과를 정리해줘.\n관련 없는 파일은 바꾸지 마.`,
  dartPlan:`선택 기업·연도·보고서로 직원수, 평균급여,\n매출액, 영업이익을 조회하려고 해.\n\n아직 수정하지 말고 사용할 OpenDART API, 요청값,\n서버 경로, 변경 파일, 결측 처리, 검증 방법을 설계해줘.`,
  env:`현재 Starter의 OPENDART_API_KEY 처리 경계를 점검해줘.\n계약을 만족하지 않는 부분만 수정해줘.\n\n- 실제 키를 코드·로그·응답에 넣지 않는다.\n- .env.example에는 변수 이름만 둔다.\n- .env가 Git에서 제외되는지 확인한다.\n- /api/health에는 설정 여부만 반환한다.\n\n검사 명령과 결과도 보여줘.`,
  corp:`기업 검색창을 /api/companies에 연결해줘.\n두 글자 이상 입력하면 검색하고 기업명·종목코드를 보여줘.\n선택하면 corp_code를 상태에 저장해줘.\n검색 중·결과 없음·오류를 구분하고 중복 선택을 막아줘.`,
  fetch:`선택 기업의 corp_code, 연도, 보고서 코드로\n재무정보와 직원현황을 함께 조회해줘.\n\n매출액·영업이익·직원수·평균급여를 corp_code로 결합하고,\n키는 브라우저로 보내지 마. 로딩·결측·오류를 구분해줘.`,
  missing:`공시 데이터 품질 규칙을 적용해줘.\n\n- 데이터 없음은 0으로 바꾸지 않는다.\n- 실제 0과 결측을 화면에서 구분한다.\n- 단위·기준연도·보고서·연결/별도 범위를 표시한다.\n- 각 값에 evidence_id를 연결한다.`,
  metric:`별도 함수로 다음 지표를 계산해줘.\n1. 인당 매출 = 매출액 / 직원수\n2. 인당 영업이익 = 영업이익 / 직원수\n3. 직원수 증가율\n4. 평균급여 증가율\n\n결측·분모 0이면 계산하지 마.\ntests/test_workforce_analytics.py에 정상값, 직원수 결측, 분모 0,\n영업이익 음수 테스트를 만들고 실행 결과를 보여줘.`,
  payload:`AI에게 원문 전체를 보내지 말고 다음만 담은 payload를 만들어줘.\n- 선택 기업과 기준연도\n- 검증된 원자료\n- 계산된 HR 지표\n- evidence_ids\n- 사용자 질문\n\n전송 전에 스키마를 검증하고 키·개인정보는 제외해줘.`,
  ai:`HR Analytics Assistant를 구현해줘.\n\n연결 계약:\n- 브라우저는 POST /api/ai/briefing으로 검증된 payload만 보낸다.\n- Provider는 OpenAI Responses API이며 모델은 OPENAI_MODEL을 사용한다.\n- 개인 키는 password 입력 → X-OpenAI-API-Key 헤더 → 서버 요청 메모리에서만 사용한다.\n- 개인 키가 없으면 서버의 OPENAI_API_KEY를 사용한다.\n- 키를 localStorage·로그·응답·오류문에 저장하거나 출력하지 않는다.\n\n답변을 확인된 사실, 계산 결과, 해석, 추가 확인 정보로 구분해줘.\n공시만으로 인과관계를 단정하거나 개인 평가·채용·보상·감축을 권고하지 못하게 하고,\n근거 ID와 한계를 표시해줘. 연결 실패·인증 실패·모델 실패도 구분해줘.`,
};

const slides=[
  page({no:1,dark:true,content:`<div class="vcenter" style="height:300pt"><p class="cover-eyebrow">HR AI AGENT BOOT CAMP · BUILD ALONG</p><h1 class="cover-title">DART API부터<br>배포까지<br>직접 만들어가기</h1><p class="cover-sub">OpenDART 키 발급 → .env → Claude Code 프롬프트 → 검증 → GitHub → Vercel</p></div><p class="cover-meta">4시간 실습 · 완성 화면보다 만드는 과정을 따라가는 강의</p>`}),
  page({no:2,kicker:'오늘 수강생이 실제로 하는 일',title:'빈 Starter를 열고, 프롬프트로 기능을 한 단계씩 붙인다',content:`<div class="content vcenter"><div class="flow"><div class="node"><strong>1 · 키 준비</strong><span>OpenDART 신청<br>.env 입력</span></div><b class="arrow">→</b><div class="node"><strong>2 · 화면</strong><span>Claude 프롬프트<br>UI 구현</span></div><b class="arrow">→</b><div class="node"><strong>3 · 데이터·AI</strong><span>API 연결<br>계산·브리핑</span></div><b class="arrow">→</b><div class="node"><strong>4 · 배포</strong><span>GitHub Push<br>Vercel URL</span></div></div><p class="body strong" style="margin-top:28pt;text-align:center">매 단계에서 “프롬프트 → 변경 파일 → 실행 결과”를 직접 확인합니다.</p></div>`}),
  page({no:3,kicker:'완성본은 목표 확인용 2분',title:'완성 화면은 한 번만 보고 바로 닫는다',subtitle:'이 화면을 설명하는 것이 오늘의 수업이 아닙니다. 지금부터 이 결과가 생기는 순서를 재현합니다.',content:`<div class="content split-40"><div class="vcenter"><p class="big">오늘의 핵심은<br><span class="accent">변화 과정</span></p><div class="rule"></div><p class="body">어떤 프롬프트를 넣었는가<br>어떤 파일이 바뀌었는가<br>무엇으로 통과를 확인했는가</p></div><div><div class="screen"><img src="./assets/current/current-compare.png" alt="최종 비교 화면"></div><p class="caption">최종 화면은 마지막 검증에서 다시 확인</p></div></div>`}),
  page({no:4,kicker:'4시간 실습 지도',title:'설명보다 입력·수정·검증 시간이 더 길다',content:`<div class="content cards4 vcenter"><div class="card"><h3>13:00–13:45</h3><p>계정·API 키<br>.env·서버·Claude</p></div><div class="card"><h3>14:00–14:45</h3><p>기본 화면과<br>선택 동작 구현</p></div><div class="card"><h3>15:00–15:45</h3><p>DART·지표·AI<br>프롬프트 구현</p></div><div class="card"><h3>16:00–16:50</h3><p>GitHub·Vercel<br>배포와 재현</p></div></div>`}),
  page({no:5,kicker:'수강생 증거물',title:'완성 화면보다 이 네 가지 기록을 제출한다',content:`<div class="content cards2"><div class="card"><h3>① 환경 설정 증거</h3><p>키 값은 가리고 health의 <b>api_key_configured: true</b>만 캡처</p></div><div class="card"><h3>② 프롬프트와 변경 증거</h3><p>Claude 요청문, 변경 파일 목록, diff 확인</p></div><div class="card"><h3>③ 기능 검증 증거</h3><p>기업 검색·실데이터 비교·결측 표시·AI 근거</p></div><div class="card"><h3>④ 배포 증거</h3><p>GitHub commit과 Vercel root·health URL</p></div></div>`}),
  section(6,'01','OpenDART 키와<br>개발 환경 준비','먼저 키를 발급받고 .env에 넣어 서버가 읽는 것까지 확인합니다.'),
  page({no:7,kicker:'수업 전 준비',title:'네 계정과 편집·실행 도구를 먼저 확인한다',content:`<div class="content cards2"><div class="card"><h3>OpenDART</h3><p>인증키 발급용 이메일과 비밀번호</p></div><div class="card"><h3>Claude Code</h3><p>로그인 가능한 Claude 계정</p></div><div class="card"><h3>GitHub · Vercel</h3><p>저장소 생성과 Import 권한</p></div><div class="card"><h3>로컬 도구</h3><p>VS Code · Python 3.11+ · Git · Chrome/Edge</p></div></div>`}),
  page({no:8,kicker:'STEP 01 · Starter 복사',title:'Starter를 복사하고 기준 커밋을 만든다',content:`<div class="content split"><div>${code(`<span class="dim">PS C:\\work&gt;</span> Copy-Item -Recurse C:\\class\\workshop_starter C:\\work\\dart-hr-agent\n<span class="dim">PS C:\\work&gt;</span> cd C:\\work\\dart-hr-agent\n<span class="dim">PS ...\\dart-hr-agent&gt;</span> git init\n<span class="dim">PS ...\\dart-hr-agent&gt;</span> git add .\n<span class="dim">PS ...\\dart-hr-agent&gt;</span> git commit -m "Save workshop starter"\n<span class="ok">[main (root-commit) ...] Save workshop starter</span>`)}</div><div class="vcenter"><div class="step"><b class="n">1</b><div><h3>Starter 복사</h3><p>원본은 복구용으로 그대로 보존</p></div></div><div class="step"><b class="n">2</b><div><h3>새 Git 시작</h3><p>개인 작업 폴더에서 초기화</p></div></div><div class="step"><b class="n">3</b><div><h3>기준 커밋</h3><p>이후 Claude 변경이 diff로 보임</p></div></div></div></div>`}),
  page({no:9,kicker:'STEP 02 · Claude Code 확인',title:'Claude Code를 실행하고 프로젝트 폴더 안인지 확인한다',content:`<div class="content split"><div>${code(`<span class="dim">PS ...\\dart-hr-agent&gt;</span> claude --version\n2.x.x\n\n<span class="dim">PS ...\\dart-hr-agent&gt;</span> claude\n\n╭─ Claude Code ─────────────╮\n│  C:\\work\\dart-hr-agent  │\n╰───────────────────────────╯\n&gt; <span class="cursor"></span>`)}</div><div class="vcenter"><div class="check"><strong>처음 실행이라면</strong><span>브라우저 로그인 안내를 따라 인증</span></div><div class="check"><strong>문제가 있다면</strong><span><code>claude doctor</code>로 설치 상태 확인</span></div><div class="check"><strong class="pass">통과</strong><span>프로젝트 경로와 프롬프트 입력창이 보임</span></div></div></div>`,source:'Claude Code 공식 설치 · docs.anthropic.com/en/docs/claude-code/getting-started'}),
  page({no:10,kicker:'STEP 03 · OpenDART 접속',title:'OpenDART에서 인증키 신청 메뉴를 연다',content:`<div class="content split-40"><div class="vcenter"><p class="body strong">1. opendart.fss.or.kr 접속</p><p class="small" style="margin-top:8pt">상단 메뉴에서 <b>인증키 신청/관리</b> → <b>인증키 신청</b></p><p class="body strong" style="margin-top:18pt">2. 개인 또는 기업 선택</p><p class="small" style="margin-top:8pt">강의용 개인 신청은 계정 신청 완료 후 즉시 발급 안내</p></div><div>${browserForm([['신청 구분','● 개인　○ 기업'],['이메일','본인 이메일 입력'],['API 사용환경','● 웹　○ 앱　○ 모두'],['API 사용용도','교육용 HR Analytics 실습']],'등록')}</div></div>`,source:'금융감독원 OpenDART 인증키 신청 · opendart.fss.or.kr/uss/umt/EgovMberInsertView.do'}),
  page({no:11,kicker:'STEP 04 · 인증키 신청',title:'약관 동의와 필수 항목을 입력하고 등록한다',content:`<div class="content"><div class="cards3"><div class="card"><h3>① 이용약관</h3><p>필수 약관과 개인정보 수집 항목 확인</p></div><div class="card"><h3>② 공통정보</h3><p>사용환경·사용용도·확인 URL 입력</p></div><div class="card"><h3>③ 등록</h3><p>메일과 인증키 관리에서 결과 확인</p></div></div><div style="margin-top:20pt;padding:15pt;border:1pt solid var(--line)"><p class="body strong">강의 전날까지 완료</p><p class="small" style="margin-top:6pt">개인 신청은 즉시 발급 안내, 기업 신청은 담당자 승인 1~2영업일 안내가 있습니다. 수업 현장에서 새 기업 계정을 만들지 않습니다.</p></div></div>`,source:'금융감독원 OpenDART 인증키 신청 화면 안내 · 2026-09-20 확인'}),
  page({no:12,kicker:'STEP 05 · 키 확인',title:'인증키 관리에서 키를 복사하되 화면에는 남기지 않는다',content:`<div class="content split"><div>${browserForm([['인증키 상태','사용 가능'],['API 인증키','••••••••••••••••••••••••••••••••••••••••'],['신청일','수업 전 발급 완료'],['이용현황','정상']],'')}</div><div class="vcenter"><div class="check"><strong>복사 직후</strong><span>.env에 한 번만 붙여넣기</span></div><div class="check"><strong>화면 공유</strong><span>키 입력 구간은 잠시 중지</span></div><div class="check"><strong>캡처</strong><span>키 값·요청 URL·헤더를 찍지 않음</span></div><div class="check"><strong class="stop">금지</strong><span>Claude 대화창이나 소스 코드에 키 붙여넣기</span></div></div></div>`}),
  page({no:13,kicker:'STEP 06 · .env 만들기',title:'.env.example을 복사해 로컬 전용 .env를 만든다',content:`<div class="content split"><div>${code(`<span class="dim">PS ...\\dart-hr-agent&gt;</span> Copy-Item .env.example .env\n\n<span class="dim">PS ...\\dart-hr-agent&gt;</span> code .env\n\n<span class="ok"># 예시 파일을 복사해\n# 변수 이름을 그대로 유지</span>`)}</div><div class="vcenter"><div class="step"><b class="n">1</b><div><h3>예시 파일 복사</h3><p>변수 이름을 틀리지 않게 유지</p></div></div><div class="step"><b class="n">2</b><div><h3>.env 열기</h3><p>프로젝트 루트 파일인지 확인</p></div></div><div class="step"><b class="n">3</b><div><h3>한 줄만 수정</h3><p><code>OPENDART_API_KEY=</code> 오른쪽</p></div></div></div></div>`}),
  page({no:14,kicker:'STEP 07 · 키 입력',title:'인증키는 .env에만 넣고 저장한다',content:`<div class="content"><div class="editor"><div class="editor-top">Visual Studio Code · .env</div><div class="editor-body"><div class="files">EXPLORER<br><span class="on">▾ dart-hr-agent</span><br>　▸ api<br>　▸ static<br>　<span class="on">● .env</span><br>　 .env.example<br>　 .gitignore<br>　 server.py</div><div class="source"><span class="comment"># OpenDART API 인증키(40자리)</span>\n<span class="key">OPENDART_API_KEY</span>=<span class="value">[여기에_본인의_40자리_인증키]</span>\n\n<span class="comment"># 서버 공용 AI 키는 선택 사항</span>\n<span class="key">OPENAI_API_KEY</span>=\n<span class="key">OPENAI_MODEL</span>=gpt-5.6-luna</div></div></div></div>`}),
  page({no:15,kicker:'STEP 08 · Git 제외 확인',title:'서버를 켜기 전에 .env가 Git에서 제외되는지 확인한다',content:`<div class="content split"><div>${code(`<span class="dim">PS ...&gt;</span> git check-ignore .env\n.env\n\n<span class="dim">PS ...&gt;</span> git ls-files .env\n<span class="dim"># 아무것도 나오지 않아야 함</span>\n\n<span class="dim">PS ...&gt;</span> git status --short\n<span class="ok"># .env가 목록에 없음</span>`)}</div><div class="vcenter"><div class="check"><strong class="pass">통과</strong><span><code>check-ignore</code>는 .env 출력, <code>ls-files</code>는 빈 결과</span></div><div class="check"><strong class="stop">중단</strong><span><code>git ls-files .env</code>가 값을 반환하면 커밋 전에 추적 해제</span></div><div class="check"><strong>캡처</strong><span>명령 결과만 찍고 .env 편집기는 닫기</span></div></div></div>`}),
  page({no:16,kicker:'STEP 09 · 서버 실행',title:'Python 서버를 실행하고 실제 로컬 주소를 연다',content:`<div class="content split"><div>${code(`<span class="dim">PS ...&gt;</span> python server.py\n\nDART HR Workshop Starter:\n<span class="ok">http://127.0.0.1:8765</span>\n\nOpenDART key configured:\n<span class="warn">True</span>`)}</div><div class="vcenter"><p class="body strong">브라우저가 자동으로 열리지 않으면</p><p class="big accent" style="font-size:28pt;margin-top:12pt">127.0.0.1:8765</p><p class="small" style="margin-top:18pt">Starter는 기본 포트 8765를 사용합니다. 포트 충돌이 나면 사용 중인 프로세스를 종료하거나 <code>PORT</code> 환경변수로 바꿉니다.</p></div></div>`}),
  page({no:17,kicker:'STEP 10 · 키 연결 확인',title:'키 값 대신 “설정됨” 상태만 확인한다',content:`<div class="content split"><div>${code(`<span class="dim">PS ...&gt;</span> $h = Invoke-RestMethod \`\n  http://127.0.0.1:8765/api/health\n\n<span class="dim">PS ...&gt;</span> $h.app.id\nkr.opendart.dart-hr-workshop-starter\n\n<span class="dim">PS ...&gt;</span> $h.api_key_configured\n<span class="ok">True</span>`)}</div><div class="vcenter"><div class="check"><strong class="pass">True면 통과</strong><span>서버가 .env에서 키를 읽었음</span></div><div class="check"><strong>False면</strong><span>파일명·위치·변수명·서버 재시작 확인</span></div><div class="check"><strong class="stop">절대 확인하지 않을 것</strong><span>키 문자열 자체를 출력하거나 공유</span></div></div></div>`}),
  page({no:18,kicker:'STEP 11 · 프롬프트 입력 방법',title:'전체 프롬프트를 붙여넣고 Enter를 누른다',content:`<div class="content split-60"><div>${code(`&gt; 이 저장소를 먼저 분석해줘.\n  아직 코드는 수정하지 마.\n\n  1. 실행 진입점\n  2. 화면 파일\n  3. OpenDART 호출 위치\n  4. 지표 계산 위치\n  5. Vercel 배포 파일\n\n  각 파일의 역할과 다음에 수정할 순서를 설명해줘.`)}</div><div class="vcenter"><div class="step"><b class="n">1</b><div><h3>프롬프트 전체 복사</h3><p>코드 블록 안의 문장만 복사</p></div></div><div class="step"><b class="n">2</b><div><h3>Claude 입력창에 붙여넣기</h3><p>API 키는 붙여넣지 않음</p></div></div><div class="step"><b class="n">3</b><div><h3>Enter 한 번</h3><p>응답이 끝날 때까지 추가 입력 금지</p></div></div></div></div>`}),
  page({no:19,kicker:'STEP 12 · 첫 Claude 프롬프트',title:'첫 요청은 코드를 만들라는 말이 아니라 “읽어달라”는 요청이다',content:`<div class="content">${prompt('PROMPT 01 · 저장소 분석',P.analyze,'붙여넣기 → Enter · 수정 승인 금지')}</div>`}),
  page({no:20,kicker:'Claude가 작업하는 동안',title:'읽는 파일과 실행하려는 명령을 화면에서 확인한다',content:`<div class="content split"><div>${code(`<span class="dim">Claude:</span> 먼저 저장소 구조를 확인하겠습니다.\n\n<span class="ok">Read</span> README.md\n<span class="ok">Read</span> server.py\n<span class="ok">Read</span> static/index.html\n<span class="ok">Read</span> static/app.js\n<span class="ok">Read</span> api/index.py\n<span class="ok">Read</span> vercel.json\n\n<span class="dim">코드는 수정하지 않았습니다.</span>`)}</div><div class="vcenter"><div class="check"><strong class="pass">허용</strong><span>파일 읽기 · 검색 · 실행 방법 확인</span></div><div class="check"><strong class="stop">멈춤</strong><span>첫 요청인데 Edit·Write·삭제를 시도함</span></div><div class="check"><strong>확인</strong><span>현재 프로젝트 경로가 맞는지 항상 보기</span></div></div></div>`}),
  page({no:21,kicker:'Claude 응답 확인',title:'답변에서 다섯 파일의 역할을 찾아 표시한다',content:`<div class="content"><table><thead><tr><th>파일</th><th>수강생이 확인할 역할</th><th>다음 단계</th></tr></thead><tbody><tr><td><code>static/index.html</code></td><td>화면 구조</td><td>UI 프롬프트</td></tr><tr><td><code>static/app.js</code></td><td>선택·요청·렌더링</td><td>DART 연결</td></tr><tr><td><code>server.py</code></td><td>.env와 API 경로</td><td>키·데이터</td></tr><tr><td><code>api/index.py</code></td><td>Vercel 진입점</td><td>배포</td></tr><tr><td><code>vercel.json</code></td><td>경로 라우팅</td><td>배포 검증</td></tr></tbody></table></div>`}),
  page({no:22,kicker:'프롬프트 작성 규칙',title:'목적·입력·규칙·완료 기준을 한 번에 준다',content:`<div class="content cards4"><div class="card"><h3>목적</h3><p>무엇을 만들 것인가</p></div><div class="card"><h3>입력</h3><p>기업·연도·보고서</p></div><div class="card"><h3>규칙</h3><p>키·결측·기존 구조</p></div><div class="card"><h3>완료 기준</h3><p>화면·명령·테스트</p></div><p class="body strong" style="grid-column:1/-1;text-align:center;margin-top:16pt">“예쁘게 만들어줘”가 아니라 검증 가능한 상태를 요청합니다.</p></div>`}),
  section(23,'02','Claude Code로<br>기본 화면 만들기','화면 뼈대 → 기업 선택 → 기간 선택 순서로 후속 기능을 붙입니다.'),
  page({no:24,active:'ui',kicker:'STEP 13 · UI 계획 요청',title:'구현 전에 변경 파일과 완료 기준부터 받는다',content:`<div class="content">${prompt('PROMPT 02 · 계획만 작성',P.uiPlan,'아직 코드를 수정하지 않도록 명시')}</div>`}),
  page({no:25,active:'ui',kicker:'Claude 계획 검토',title:'계획이 이번 범위를 넘으면 구현 전에 줄인다',content:`<div class="content split"><div class="vcenter"><div class="check"><strong>이번 단계에 포함</strong><span>화면 뼈대와 빈 상태</span></div><div class="check"><strong>다음 프롬프트로 미룸</strong><span>선택 동작 · 기간 · 실제 API · AI</span></div><div class="check"><strong>변경 파일</strong><span><code>static/index.html</code> · <code>static/styles.css</code></span></div></div><div class="vcenter" style="border-left:1pt solid var(--line);padding-left:24pt"><p class="body strong">계획이 맞으면 입력</p><p class="big accent" style="font-size:25pt;margin-top:12pt">“첫 단계만 진행해줘.”</p><p class="small" style="margin-top:12pt">한 번에 전체 앱을 만들지 않습니다.</p></div></div>`}),
  page({no:26,active:'ui',kicker:'STEP 14 · 첫 화면 구현',title:'서비스 제목과 입력 영역만 만드는 프롬프트를 넣는다',content:`<div class="content">${prompt('PROMPT 03 · 화면 뼈대',P.uiShell)}</div>`}),
  page({no:27,active:'ui',kicker:'수정 승인 화면',title:'파일 경로와 수정 내용을 보고 승인한다',content:`<div class="content split"><div>${code(`<span class="dim">Claude wants to edit:</span>\n<span class="ok">static/index.html</span>\n  + service header\n  + company search input\n  + empty result area\n<span class="ok">static/styles.css</span>\n  + layout and input styles\n\nMake this edit?\n<span class="warn">❯ 1. Yes</span>    2. No`)}</div><div class="vcenter"><div class="check"><strong>Yes 선택</strong><span>계획한 파일과 내용이 맞을 때</span></div><div class="check"><strong>No 선택</strong><span>API·AI·새 라이브러리가 섞였을 때</span></div><div class="check"><strong>승인 후</strong><span>Claude의 완료 문구가 아니라 diff 확인</span></div></div></div>`}),
  page({no:28,active:'ui',kicker:'STEP 15 · 첫 변경 확인',title:'파일이 만들어진 뒤 terminal에서 diff를 본다',content:`<div class="content split"><div>${code(`<span class="dim">PS ...&gt;</span> git status --short\n M static/index.html\n M static/styles.css\n\n<span class="dim">PS ...&gt;</span> git diff --stat\n static/index.html | 28 +++++\n static/styles.css | 54 +++++++++\n\n<span class="dim">PS ...&gt;</span> git diff`)}</div><div class="vcenter"><div class="check"><strong>요청한 요소</strong><span>제목 · 소개 · 검색창 · 선택 영역 · 빈 상태</span></div><div class="check"><strong>아직 없어야 할 것</strong><span>실제 API 호출 · AI 호출 · API 키</span></div></div></div>`}),
  page({no:29,active:'ui',kicker:'STEP 16 · 기능 추가 프롬프트',title:'같은 대화에서 기업 선택 동작만 추가한다',content:`<div class="content">${prompt('PROMPT 04 · 기업 선택 추가',P.addSelection,'기존 결과를 유지한 채 한 기능만 추가')}</div>`}),
  page({no:30,active:'ui',kicker:'기업 선택 결과 확인',title:'프롬프트 한 번으로 화면 상태가 어떻게 바뀌었는지 비교한다',content:`<div class="content split"><div class="card vcenter"><span class="badge">BEFORE</span><h3 style="margin-top:12pt">검색창만 있음</h3><p>입력해도 결과·선택 상태 없음</p></div><div class="card vcenter" style="border-top-color:var(--green)"><span class="badge">AFTER PROMPT 04</span><h3 style="margin-top:12pt">검색 결과와 0/2 선택</h3><p>추가·삭제·중복 방지 동작 확인</p></div></div>`}),
  page({no:31,active:'ui',kicker:'STEP 17 · 다음 기능 추가',title:'기업 선택은 유지하고 기간과 비교 버튼만 붙인다',content:`<div class="content">${prompt('PROMPT 05 · 기간과 비교 버튼',P.addPeriod)}</div>`}),
  page({no:32,active:'ui',kicker:'STEP 18 · 브라우저 검증',title:'서버를 다시 열고 추가된 기능을 손으로 조작한다',content:`<div class="content split-60"><div><div class="screen"><img src="./assets/current/current-home.png" alt="기업과 기간 선택 화면"></div><p class="caption">직접 확인: 입력창 · 선택 목록 · 연도 · 보고서 · 비교 버튼</p></div><div class="vcenter"><div class="check"><strong>기업 검색 입력</strong><span>검색 결과와 0/2 상태</span></div><div class="check"><strong>선택 추가·삭제</strong><span>중복 없이 두 기업 표시</span></div><div class="check"><strong>조건 변경</strong><span>이전 결과가 남지 않음</span></div></div></div>`}),
  page({no:33,active:'ui',kicker:'문제가 생겼을 때',title:'오류 화면을 그대로 보여주고 작은 수정만 요청한다',content:`<div class="content">${prompt('PROMPT 06 · 오류 수정',P.fix,'오류 복사 → 원인 축소 → 작은 수정 → 같은 동작 재검증')}</div>`}),
  page({no:34,active:'ui',kicker:'MODULE 02 체크포인트 · 14:45',title:'프롬프트 세 번으로 화면이 자라는 과정을 설명해야 통과한다',content:`<div class="content split"><div class="vcenter"><div class="check"><strong class="pass">PROMPT 03</strong><span>화면 뼈대 생성</span></div><div class="check"><strong class="pass">PROMPT 04</strong><span>기업 선택 동작 추가</span></div><div class="check"><strong class="pass">PROMPT 05</strong><span>기간·보고서·비교 버튼 추가</span></div></div><div class="vcenter"><p class="body strong">남겨야 할 증거</p><p class="small" style="margin-top:9pt">전체 프롬프트<br>Claude 수정 승인 화면<br><code>git diff --stat</code><br>브라우저 Before/After</p></div></div>`}),
  section(29,'03','OpenDART 연결과<br>HR 지표·AI 구현','API 호출도 같은 순서입니다. 먼저 설계하고, 한 경로씩 붙이고, 실제 응답으로 검증합니다.'),
  page({no:30,active:'data',kicker:'STEP 19 · 데이터 흐름',title:'브라우저에 키를 보내지 않고 서버가 OpenDART를 호출한다',content:`<div class="content vcenter"><div class="flow"><div class="node"><strong>브라우저</strong><span>기업·연도·보고서</span></div><b class="arrow">→</b><div class="node"><strong>Python 서버</strong><span>.env의 키 결합</span></div><b class="arrow">→</b><div class="node"><strong>OpenDART</strong><span>공시 JSON·XML</span></div><b class="arrow">→</b><div class="node"><strong>검증·화면</strong><span>정규화·근거 ID</span></div></div><p class="body strong" style="text-align:center;margin-top:24pt">키는 OpenDART HTTPS 요청에만 포함되고 브라우저로 돌아오지 않습니다.</p></div>`}),
  page({no:31,active:'data',kicker:'사용할 OpenDART 데이터',title:'세 API와 요청값의 차이를 먼저 고정한다',content:`<div class="content"><table><thead><tr><th>목적</th><th>API·파일</th><th>핵심 결과</th></tr></thead><tbody><tr><td>기업 검색</td><td><code>corpCode.xml</code></td><td><code>corp_code</code> 8자리</td></tr><tr><td>재무정보</td><td><code>fnlttSinglAcnt.json</code></td><td>매출액·영업이익</td></tr><tr><td>직원현황</td><td><code>empSttus.json</code></td><td>직원수·평균급여</td></tr></tbody></table><p class="small" style="margin-top:14pt">공통: <code>crtfc_key</code> · 기업목록 ZIP: 키만 · 재무/직원: <code>corp_code</code> + <code>bsns_year</code> + <code>reprt_code</code></p></div>`,source:'OpenDART 개발가이드 · opendart.fss.or.kr/guide/main.do'}),
  page({no:32,active:'data',kicker:'STEP 20 · API 설계 요청',title:'실제 코드를 쓰기 전에 호출·결측·검증 계획을 받는다',content:`<div class="content">${prompt('PROMPT 07 · OpenDART 연결 계획',P.dartPlan,'계획만 작성 · 엔드포인트와 요청값을 사람이 대조')}</div>`}),
  page({no:33,active:'data',kicker:'STEP 21 · 서버 키 경계 검증',title:'.env를 읽는 위치와 health 응답이 안전한지 Claude로 검사한다',content:`<div class="content">${prompt('PROMPT 08 · 환경변수 경계',P.env)}</div>`}),
  page({no:34,active:'data',kicker:'STEP 22 · 기업 검색 구현',title:'화면 검색어를 DART corp_code로 바꾸는 경로를 붙인다',content:`<div class="content">${prompt('PROMPT 09 · 기업 검색',P.corp)}</div>`}),
  page({no:341,active:'data',kicker:'API 연결 1 · 브라우저 코드',title:'검색어를 우리 서버의 /api/companies로 보낸다',content:`<div class="content split-60"><div>${code(`<span class="dim">// static/app.js</span>\nconst query = companySearch.value.trim();\n\nconst response = await fetch(\n  \`/api/companies?q=\${encodeURIComponent(query)}\`\n);\n\nconst payload = await response.json();\nrenderSearchResults(payload.companies || []);`)}</div><div class="vcenter"><div class="check"><strong>브라우저가 보내는 것</strong><span>검색어 <code>q=삼성전자</code></span></div><div class="check"><strong>브라우저가 보내지 않는 것</strong><span>OpenDART 인증키</span></div><div class="check"><strong>확인할 파일</strong><span><code>static/app.js</code></span></div></div></div>`}),
  page({no:342,active:'data',kicker:'API 연결 2 · 서버 경로',title:'Python 서버가 검색어를 받고 기업 목록을 반환한다',content:`<div class="content split-60"><div>${code(`<span class="dim"># server.py</span>\nif parsed.path == "/api/companies":\n    query = parse_qs(parsed.query).get("q", [""])[0]\n    companies = search_companies(query)\n    self.send_json({"companies": companies})\n    return`)}</div><div class="vcenter"><div class="check"><strong>입력</strong><span><code>/api/companies?q=삼성전자</code></span></div><div class="check"><strong>처리</strong><span><code>search_companies(query)</code></span></div><div class="check"><strong>출력</strong><span>기업명·종목코드·corp_code JSON</span></div></div></div>`}),
  page({no:343,active:'data',kicker:'API 연결 3 · OpenDART 요청',title:'키를 붙여 받은 ZIP을 서버에서 XML로 푼다',content:`<div class="content split-60"><div>${code(`<span class="dim"># server.py</span>\nimport json\nfrom io import BytesIO\nfrom zipfile import ZipFile\n\ndef dart_request(endpoint, params, *, binary=False):\n    if not API_KEY:\n        raise DARTError("키가 설정되지 않았습니다")\n    query = {**params, "crtfc_key": API_KEY}\n    url = f"{DART_BASE}/{endpoint}?{urlencode(query)}"\n    with urlopen(url, timeout=10) as response:\n        return response.read() if binary else json.load(response)\n\nzip_bytes = dart_request("corpCode.xml", {}, binary=True)\nwith ZipFile(BytesIO(zip_bytes)) as archive:\n    corp_xml = archive.read("CORPCODE.xml")`,true)}</div><div class="vcenter"><p class="body strong">연결 경계</p><p class="small" style="margin-top:8pt">브라우저 → 우리 서버: 검색어만<br>우리 서버 → OpenDART: 인증키를 HTTPS 요청에 결합<br>우리 서버: ZIP 해제·XML 파싱<br>우리 서버 → 브라우저: 정리된 JSON만</p><div class="check" style="margin-top:12pt"><strong class="stop">키가 보이면 실패</strong><span>브라우저 Network·응답 JSON·로그에 키가 없어야 함</span></div></div></div>`}),
  page({no:344,active:'data',kicker:'API 연결 4 · 응답 확인',title:'브라우저 주소창에서 우리 API의 JSON을 먼저 확인한다',content:`<div class="content split"><div>${code(`<span class="dim">GET</span> http://127.0.0.1:8765/\n    api/companies?q=삼성전자\n\n{\n  "companies": [\n    {\n      "corp_name": "삼성전자",\n      "stock_code": "005930",\n      "corp_code": "00126380"\n    }\n  ]\n}`)}</div><div class="vcenter"><div class="step"><b class="n">1</b><div><h3>HTTP 200</h3><p>우리 서버 경로가 열림</p></div></div><div class="step"><b class="n">2</b><div><h3>companies 배열</h3><p>화면이 사용할 JSON 계약</p></div></div><div class="step"><b class="n">3</b><div><h3>키 문자열 없음</h3><p>비밀이 서버 밖으로 나오지 않음</p></div></div></div></div>`}),
  page({no:35,active:'data',kicker:'STEP 23 · 기업 검색 검증',title:'검색 결과에서 회사명·종목코드·corp_code를 확인한다',content:`<div class="content split-60"><div><div class="screen"><img src="./assets/company-search.png" alt="기업 검색 결과"></div><p class="caption">실제 앱 조작 캡처 · 키 문자열은 화면에 없음</p></div><div class="vcenter"><div class="check"><strong>입력</strong><span>삼성전자 또는 종목코드</span></div><div class="check"><strong>응답</strong><span>법인명 · 종목코드 · 8자리 식별자</span></div><div class="check"><strong>예외</strong><span>검색 중 · 결과 없음 · API 오류</span></div></div></div>`}),
  page({no:36,active:'data',kicker:'STEP 24 · 재무·직원 데이터 구현',title:'두 API 결과를 같은 corp_code와 기간으로 결합한다',content:`<div class="content">${prompt('PROMPT 10 · 핵심 데이터 수집',P.fetch)}</div>`}),
  page({no:361,active:'data',kicker:'재무·직원 연결 1 · 브라우저 요청',title:'선택한 corp_code와 기간을 우리 서버 경로로 보낸다',content:`<div class="content split-60"><div>${code(`<span class="dim">// static/app.js</span>\nconst query = new URLSearchParams({\n  corp_codes: selected.map(c =&gt; c.corp_code).join(","),\n  year: "2024",\n  report_code: "11011"\n});\n\nawait Promise.all([\n  fetch(\`/api/financials?\${query}\`),\n  fetch(\`/api/people?\${query}\`)\n]);`)}</div><div class="vcenter"><div class="check"><strong><code>corp_codes</code></strong><span>선택 기업의 DART 식별자</span></div><div class="check"><strong><code>year</code></strong><span>사업연도</span></div><div class="check"><strong><code>report_code</code></strong><span>11011 = 사업보고서</span></div></div></div>`}),
  page({no:362,active:'data',kicker:'재무·직원 연결 2 · 서버가 OpenDART 호출',title:'같은 기간 파라미터를 두 OpenDART API에 전달한다',content:`<div class="content split"><div>${code(`<span class="dim"># 재무정보</span>\ndart_request(\n  "fnlttSinglAcnt.json",\n  {"corp_code": code,\n   "bsns_year": year,\n   "reprt_code": report_code}\n)`)}</div><div>${code(`<span class="dim"># 직원현황</span>\ndart_request(\n  "empSttus.json",\n  {"corp_code": code,\n   "bsns_year": year,\n   "reprt_code": report_code}\n)`)}</div></div>`}),
  page({no:363,active:'data',kicker:'재무·직원 연결 3 · 응답 결합',title:'corp_code를 열쇠로 두 응답을 한 기업 행으로 합친다',content:`<div class="content split-60"><div>${code(`{\n  "example": "교육용 예시",\n  "corp_code": "00126380",\n  "year": "2024",\n  "report_code": "11011",\n  "financials": {\n    "revenue": 300000000000000,\n    "operating_profit": 26000000000000\n  },\n  "people": {\n    "employees_total": 120000,\n    "average_salary": 130000000\n  }\n}`,true)}</div><div class="vcenter"><div class="check"><strong>결합 기준</strong><span><code>corp_code + year + report_code</code></span></div><div class="check"><strong>숫자 주의</strong><span>화면의 숫자는 구조 설명용 예시</span></div><div class="check"><strong>다음 단계</strong><span>실제 응답에 결측·단위·근거 규칙 적용</span></div></div></div>`}),
  page({no:37,active:'data',kicker:'STEP 25 · 데이터 품질 규칙',title:'값이 없을 때 0으로 보이면 분석이 틀어진다',content:`<div class="content">${prompt('PROMPT 11 · 결측과 근거',P.missing)}</div>`}),
  page({no:38,active:'data',kicker:'STEP 26 · 실제 데이터 검증',title:'비교 결과에서 값·단위·근거를 직접 확인한다',content:`<div class="content split-60"><div><div class="screen"><img src="./assets/current/current-compare.png" alt="두 기업의 실제 비교 결과"></div><p class="caption">기업·연도·보고서 선택 → 비교 실행 → 결과 카드 확인</p></div><div class="vcenter"><div class="check"><strong>확인 1</strong><span>두 기업 모두 같은 기간인가</span></div><div class="check"><strong>확인 2</strong><span>원자료 단위와 범위가 보이는가</span></div><div class="check"><strong>확인 3</strong><span>결측과 실제 0이 구분되는가</span></div><div class="check"><strong>확인 4</strong><span>DART 근거 링크가 기업에 맞는가</span></div></div></div>`}),
  page({no:39,active:'data',kicker:'STEP 27 · HR 지표 계산',title:'공시 원자료를 계산 함수로 바꾸는 프롬프트를 넣는다',content:`<div class="content">${prompt('PROMPT 12 · 파생지표',P.metric)}</div>`}),
  page({no:40,active:'data',kicker:'STEP 28 · 계산 검증',title:'정상값 하나보다 결측·0·음수 사례를 함께 본다',content:`<div class="content split"><div>${code(`<span class="dim">PS ...&gt;</span> python -m unittest \`\n  tests/test_workforce_analytics.py -v\n\ntest_revenue_per_employee ... <span class="ok">ok</span>\ntest_missing_employees ... <span class="ok">ok</span>\ntest_zero_denominator ... <span class="ok">ok</span>\ntest_negative_profit ... <span class="ok">ok</span>\n\n<span class="ok">Ran 4 tests · OK</span>`)}</div><div class="vcenter"><p class="body strong">사람이 계산기로 한 번 대조</p><p class="small" style="margin-top:10pt">매출액 ÷ 직원수<br>영업이익 ÷ 직원수<br>전년값이 있을 때만 증가율</p><p class="small" style="margin-top:16pt">단위가 원·천원·백만원 중 무엇인지 먼저 확인합니다.</p></div></div>`}),
  page({no:41,active:'data',kicker:'STEP 29 · AI 입력 계약',title:'AI에게 문서 전체가 아니라 검증된 숫자만 보낸다',content:`<div class="content">${prompt('PROMPT 13 · AI payload',P.payload)}</div>`}),
  page({no:42,active:'data',kicker:'AI에게 전달되는 모양',title:'질문과 숫자, 계산, 근거 ID가 한 묶음이 된다',content:`<div class="content split-60"><div>${code(`{\n  "company": "A사",\n  "year": "2024",\n  "employees": 10000,\n  "revenue": 20000000000000,\n  "revenue_per_employee": 2000000000,\n  "evidence_ids": ["FIN-A-2024", "EMP-A-2024"],\n  "question": "생산성 차이를 설명해줘"\n}`)}</div><div class="vcenter"><div class="check"><strong>포함</strong><span>공개 기업 집계·계산값·근거 ID</span></div><div class="check"><strong>제외</strong><span>API 키·개인정보·원문 전체</span></div><div class="check"><strong>검증</strong><span>전송 전 스키마와 질문 범위 확인</span></div></div></div>`}),
  page({no:43,active:'data',kicker:'STEP 30 · AI 브리핑 구현',title:'Provider·경로·키 수명까지 프롬프트에 적는다',content:`<div class="content">${prompt('PROMPT 14 · HR Analytics Assistant',P.ai,'연결 계약 확인 → 구현 승인 → 네트워크·로그 검증',true)}</div>`}),
  page({no:431,active:'data',kicker:'AI 연결 1 · 브라우저 요청',title:'검증된 payload와 선택적 개인 키를 우리 서버로 보낸다',content:`<div class="content split-60"><div>${code(`<span class="dim">// static/app.js</span>\nconst headers = {"Content-Type": "application/json"};\nconst personalKey = aiKey.value.trim();\nif (personalKey) {\n  headers["X-OpenAI-API-Key"] = personalKey;\n}\n\nconst response = await fetch("/api/ai/briefing", {\n  method: "POST",\n  headers,\n  body: JSON.stringify(validatedPayload)\n});`,true)}</div><div class="vcenter"><div class="check"><strong>개인 키가 있으면</strong><span>password 입력값을 이 요청에만 사용</span></div><div class="check"><strong>개인 키가 없으면</strong><span>서버의 <code>OPENAI_API_KEY</code> 사용</span></div><div class="check"><strong class="stop">저장 금지</strong><span>localStorage·소스·응답·로그</span></div></div></div>`}),
  page({no:432,active:'data',kicker:'AI 연결 2 · 서버 Provider 호출',title:'서버가 Responses API를 호출해 답변만 반환한다',content:`<div class="content split-60"><div>${code(`<span class="dim"># server.py · POST /api/ai/briefing</span>\nheader_key = self.headers.get("X-OpenAI-API-Key")\nkey = header_key or OPENAI_API_KEY\nbody = json.dumps({\n  "model": OPENAI_MODEL,\n  "input": briefing_prompt(payload)\n}).encode("utf-8")\nrequest = Request(\n  "https://api.openai.com/v1/responses",\n  data=body, method="POST",\n  headers={"Authorization": f"Bearer {key}",\n           "Content-Type": "application/json"}\n)\nresult = json.load(urlopen(request, timeout=30))\nanswer = extract_output_text(result)\nself.send_json({"answer": answer})`,true)}</div><div class="vcenter"><div class="check"><strong>모델</strong><span><code>OPENAI_MODEL=gpt-5.6-luna</code></span></div><div class="check"><strong>키 수명</strong><span>현재 HTTPS 요청 처리 동안만 메모리에 존재</span></div><div class="check"><strong>반환</strong><span>검증된 답변 텍스트와 근거 ID만</span></div></div></div>`,source:'OpenAI Responses API 공식 문서 · platform.openai.com/docs/api-reference/responses'}),
  page({no:44,active:'data',kicker:'STEP 31 · 질문 실행',title:'질문을 넣고 답변보다 근거 구조를 검사한다',content:`<div class="content split-60"><div><div class="screen"><img src="./assets/current/current-ai.png" alt="AI 질문 결과"></div><p class="caption">직접 실행 캡처 · 공개 기업 집계 또는 합성 데이터만 사용</p></div><div class="vcenter"><p class="body strong">질문 예시</p><p class="small" style="margin-top:7pt">“두 기업의 인당 생산성 차이를 공시 근거와 함께 설명해줘.”</p><div class="check" style="margin-top:15pt"><strong>답변 검사</strong><span>사실 · 계산 · 해석 · 추가 확인이 구분되는가</span></div><div class="check"><strong>금지 검사</strong><span>개인 판단·인과 단정·자동 인사조치가 없는가</span></div></div></div>`}),
  page({no:45,active:'data',kicker:'MODULE 03 체크포인트 · 15:45',title:'프롬프트에서 실제 공시와 근거 있는 답변까지 이어져야 통과한다',content:`<div class="content cards2"><div class="card"><h3>데이터 통과</h3><p>검색 → corp_code → 재무·직원 API → 결측·근거 표시</p></div><div class="card"><h3>계산 통과</h3><p>인당 지표와 결측·분모 0 테스트</p></div><div class="card"><h3>AI 통과</h3><p>payload → 서버 → Provider → 근거 있는 답변</p></div><div class="card"><h3>증거 통과</h3><p>PROMPT 07~14 · diff · 테스트 · Network</p></div></div>`}),
  section(46,'04','GitHub에 저장하고<br>Vercel에 배포하기','이제 만들어진 코드를 비밀값 없이 저장하고, 실제 URL에서 같은 동작을 재현합니다.'),
  page({no:47,active:'deploy',kicker:'STEP 32 · 업로드 전 검사',title:'git add 전에 .env와 키가 빠졌는지 다시 확인한다',content:`<div class="content split"><div>${code(`<span class="dim">PS ...&gt;</span> git status --short\n<span class="dim">PS ...&gt;</span> git check-ignore .env\n.env\n<span class="dim">PS ...&gt;</span> git ls-files .env\n<span class="dim"># 빈 결과</span>\n\n<span class="dim">PS ...&gt;</span> git grep -n OPENDART_API_KEY -- . ":!.env"\n.env.example:OPENDART_API_KEY`)}</div><div class="vcenter"><div class="check"><strong class="pass">계속</strong><span>예시 파일에는 변수 이름만 존재</span></div><div class="check"><strong class="stop">즉시 중단</strong><span>실제 키·개인정보·.env가 추적됨</span></div><div class="check"><strong>수정 후</strong><span>키를 폐기·재발급하고 검사부터 다시 실행</span></div></div></div>`}),
  page({no:48,active:'deploy',kicker:'STEP 33 · GitHub 저장소 생성',title:'github.com/new에서 빈 저장소를 만든다',content:`<div class="content split-40"><div class="vcenter"><div class="step"><b class="n">1</b><div><h3>Repository name</h3><p><code>dart-hr-agent</code></p></div></div><div class="step"><b class="n">2</b><div><h3>Public 또는 Private</h3><p>강의 제출 기준에 맞게 선택</p></div></div><div class="step"><b class="n">3</b><div><h3>초기화 옵션 끄기</h3><p>README·.gitignore·License 추가 안 함</p></div></div></div><div class="browser"><div class="browser-top">🔒 github.com/new</div><div class="browser-body"><p class="body strong">Create a new repository</p><div class="mock-form"><div class="mock-row"><b>Owner</b><span>본인 계정</span></div><div class="mock-row"><b>Repository</b><span>dart-hr-agent</span></div><div class="mock-row"><b>Visibility</b><span>● Public　○ Private</span></div><div class="mock-row"><b>Initialize</b><span>□ README　□ .gitignore</span></div></div><span class="mock-button">Create repository</span></div></div></div>`}),
  page({no:49,active:'deploy',kicker:'STEP 34 · 기능 커밋과 Push',title:'기준 커밋 뒤의 변경만 검토해 원격 저장소로 보낸다',content:`<div class="content split-60"><div>${code(`<span class="dim">PS ...&gt;</span> git status --short\n<span class="dim">PS ...&gt;</span> git diff\n<span class="dim">PS ...&gt;</span> git add .\n<span class="dim">PS ...&gt;</span> git diff --cached --name-only\n<span class="dim">PS ...&gt;</span> git diff --cached\n\n<span class="dim">PS ...&gt;</span> git commit -m "Build DART HR agent"\n<span class="dim">PS ...&gt;</span> git branch -M main\n<span class="dim">PS ...&gt;</span> git remote add origin https://github.com/ID/dart-hr-agent.git\n<span class="dim">PS ...&gt;</span> git push -u origin main`)}</div><div class="vcenter"><p class="body strong">멈춰서 볼 지점</p><p class="small" style="margin-top:8pt">① 기준 커밋 이후의 실제 diff<br>② <code>add</code> 뒤 staged 파일<br>③ remote가 본인 저장소인지<br>④ push가 <code>main → main</code>인지</p></div></div>`}),
  page({no:50,active:'deploy',kicker:'STEP 35 · GitHub 웹 검증',title:'저장소 웹 화면에서 코드와 비밀 분리를 확인한다',content:`<div class="content cards2"><div class="card"><h3>README</h3><p>실행 명령과 .env 생성 방법</p></div><div class="card"><h3>배포 파일</h3><p><code>api/index.py</code> · <code>vercel.json</code></p></div><div class="card"><h3>최신 커밋</h3><p>로컬 <code>git log -1</code>과 같은 해시</p></div><div class="card"><h3>.env 없음</h3><p>검색해도 실제 키 파일이 나오지 않음</p></div></div>`}),
  page({no:51,active:'deploy',kicker:'STEP 36 · Vercel Import',title:'vercel.com/new에서 방금 Push한 저장소를 가져온다',content:`<div class="content split-40"><div class="vcenter"><div class="step"><b class="n">1</b><div><h3>Add New Project</h3><p>GitHub 연결 권한 확인</p></div></div><div class="step"><b class="n">2</b><div><h3>Repository 선택</h3><p><code>dart-hr-agent</code> Import</p></div></div><div class="step"><b class="n">3</b><div><h3>Project 설정</h3><p>Framework: Other · Root: ./</p></div></div></div><div class="browser"><div class="browser-top">🔒 vercel.com/new</div><div class="browser-body"><p class="body strong">Import Git Repository</p><div class="mock-form"><div class="mock-row"><b>Repository</b><span>본인ID / dart-hr-agent</span></div><div class="mock-row"><b>Framework</b><span>Other</span></div><div class="mock-row"><b>Root Directory</b><span>./</span></div><div class="mock-row"><b>Build / Output</b><span>기본값 유지</span></div></div><span class="mock-button">Import</span></div></div></div>`,source:'Vercel Git 배포 공식 문서 · vercel.com/docs/git'}),
  page({no:52,active:'deploy',kicker:'STEP 37 · Vercel 환경변수',title:'Production 환경에 OpenDART 키를 다시 등록한다',content:`<div class="content split"><div class="editor"><div class="editor-top">Vercel · Settings · Environment Variables</div><div class="editor-body" style="grid-template-columns:150pt 1fr"><div class="files"><span class="on">Environment</span><br>Domains<br>Git<br>Functions<br>Deployment Protection</div><div class="source" style="font-family:inherit;font-size:11.5pt"><b>Key</b>\n<span class="key">OPENDART_API_KEY</span>\n\n<b>Value</b>\n<span class="value">••••••••••••••••••••</span>\n\n<b>Target</b>\nProduction\n\n<span class="key">Sensitive ON</span></div></div></div><div class="vcenter"><div class="check"><strong>이름</strong><span><code>OPENDART_API_KEY</code> 정확히 입력</span></div><div class="check"><strong>대상</strong><span>Production 선택</span></div><div class="check"><strong>보호</strong><span>Sensitive 활성화</span></div><div class="check"><strong>AI 키</strong><span>개인 키 입력 방식이면 서버 등록 생략</span></div></div></div>`,source:'Vercel 환경변수 공식 문서 · vercel.com/docs/environment-variables/managing-environment-variables'}),
  page({no:53,active:'deploy',kicker:'STEP 38 · Deploy',title:'Deploy를 누르고 Ready보다 Build Logs를 먼저 읽는다',content:`<div class="content"><div class="flow"><div class="node"><strong>Queued</strong><span>배포 대기</span></div><b class="arrow">→</b><div class="node"><strong>Building</strong><span>Python 함수·정적 파일</span></div><b class="arrow">→</b><div class="node"><strong>Ready</strong><span>도메인 생성</span></div><b class="arrow">→</b><div class="node"><strong>Verify</strong><span>root·health·검색</span></div></div><div style="margin-top:22pt;border:1pt solid var(--line);padding:12pt 14pt"><p class="body strong">Building에서 멈추면</p><p class="small" style="margin-top:5pt">Build Logs의 첫 번째 오류부터 읽고, 그 문장을 Claude Code에 붙여넣어 원인·수정 파일·재배포 방법을 요청합니다.</p></div></div>`}),
  page({no:54,active:'deploy',kicker:'STEP 39 · 운영 URL 검증',title:'배포 URL에서 로컬과 같은 순서로 다시 조작한다',content:`<div class="content split"><div class="vcenter"><div class="step"><b class="n">1</b><div><h3>루트 화면</h3><p><code>https://프로젝트.vercel.app/</code></p></div></div><div class="step"><b class="n">2</b><div><h3>health</h3><p><code>/api/health</code> · api_key_configured: true</p></div></div><div class="step"><b class="n">3</b><div><h3>기업 검색</h3><p>실제 OpenDART 검색 1회</p></div></div><div class="step"><b class="n">4</b><div><h3>비밀 확인</h3><p>소스·응답·URL에 키가 없음</p></div></div></div><div><div class="screen"><img src="./assets/production.png" alt="Vercel 운영 화면"></div><p class="caption">운영 화면과 health가 같은 배포 commit을 가리키는지 확인</p></div></div>`}),
  page({no:55,active:'deploy',kicker:'STEP 40 · 수정 후 자동 재배포',title:'코드를 고치면 같은 검증 루프를 한 번 더 돈다',content:`<div class="content vcenter"><div class="flow"><div class="node"><strong>Claude 수정</strong><span>작은 범위</span></div><b class="arrow">→</b><div class="node"><strong>로컬 검증</strong><span>diff·test·browser</span></div><b class="arrow">→</b><div class="node"><strong>commit · push</strong><span>main 갱신</span></div><b class="arrow">→</b><div class="node"><strong>Vercel</strong><span>새 Production</span></div></div><p class="body strong" style="text-align:center;margin-top:25pt">환경변수만 바꿔도 새 배포 또는 Redeploy가 필요합니다.</p></div>`}),
  page({no:56,active:'deploy',kicker:'MODULE 04 체크포인트 · 16:40',title:'저장소와 URL이 같은 코드를 보여줘야 통과한다',content:`<div class="content cards2"><div class="card"><h3>GitHub 증거</h3><p>저장소 URL · 최신 commit · .env 없음</p></div><div class="card"><h3>Vercel 증거</h3><p>Production URL · Ready · 연결 commit</p></div><div class="card"><h3>실행 증거</h3><p>root · health · 기업 검색 · 비교</p></div><div class="card"><h3>과정 증거</h3><p>프롬프트 01~14 · diff · 테스트 결과</p></div></div>`}),
  page({no:57,dark:true,content:`<div class="vcenter" style="height:305pt"><p class="cover-eyebrow">FINAL REPLAY</p><h1 class="cover-title" style="font-size:42pt">키를 넣고<br>프롬프트로 만들고<br>검증해서 배포했다</h1><p class="cover-sub">OpenDART 인증키 → .env → Claude Code → DART·HR·AI → GitHub → Vercel</p></div><p class="cover-meta">제출: 프롬프트 기록 · 변경 diff · GitHub commit · 실제 Web URL</p>`}),
];

for(const file of fs.readdirSync(deckDir)){if(/^slide-\d+\.html$/.test(file))fs.unlinkSync(path.join(deckDir,file))}
slides.forEach((html,index)=>fs.writeFileSync(path.join(deckDir,`slide-${String(index+1).padStart(2,'0')}.html`),html,'utf8'));

const titles=slides.map((html,index)=>{
  const match=html.match(/<h1[^>]*>([\s\S]*?)<\/h1>/i);
  return match ? match[1].replace(/<br\s*\/?\s*>/gi,' ').replace(/<[^>]+>/g,'').trim() : `실습 단계 ${index+1}`;
});
const outline=`# DART API부터 배포까지 직접 만들어가기\n\n## Meta\n- Slide count: ${slides.length}\n- Aspect ratio: 16:9\n- Teaching model: 화면 설명이 아니라 실제 제작 순서 재현\n- Core loop: 프롬프트 → 변경 파일 → diff → 실행 → 체크포인트\n\n## Slide map\n${titles.map((t,i)=>`- ${String(i+1).padStart(2,'0')}. ${t}`).join('\n')}\n`;
fs.writeFileSync(path.join(deckDir,'slide-outline.md'),outline,'utf8');

const promptDoc=`# 수강생용 Claude Code 실습 프롬프트\n\n아래 프롬프트를 순서대로 사용합니다. 실제 API 키는 어떤 프롬프트에도 입력하지 않습니다. 각 단계에서 Claude가 제안한 변경 파일을 확인하고, 적용 뒤에는 반드시 \`git diff\`와 브라우저를 확인합니다.\n\n${Object.entries(P).map(([key,value],index)=>`## ${String(index+1).padStart(2,'0')}. ${key}\n\n\`\`\`text\n${value}\n\`\`\``).join('\n\n')}\n\n## 공통 검증 프롬프트\n\n\`\`\`text\n방금 변경한 내용을 검증해줘. 수정 파일 목록, 실행한 검사, 통과 결과, 아직 남은 위험을 구분해서 보여줘. 실제 API 키나 개인정보는 출력하지 마.\n\`\`\`\n\n## 오류 수정 프롬프트\n\n\`\`\`text\n${P.fix}\n\`\`\`\n`;
fs.writeFileSync(path.join(deckDir,'participant-prompts.md'),promptDoc,'utf8');

const moduleActions={
  setup:'수강생 화면에서 계정·키·.env·서버·Claude 입력을 직접 따라 하게 합니다.',
  ui:'프롬프트를 붙여넣고 계획·변경 파일·diff·브라우저 결과를 차례로 확인합니다.',
  data:'OpenDART 연결, 결측, 계산, AI Provider 경로를 한 기능씩 구현하고 매번 실행합니다.',
  deploy:'GitHub와 Vercel에서 실제 URL이 생길 때까지 진행하고 원격 commit을 대조합니다.',
};
const notes=`# 발표자 노트\n\n이 덱은 완성 프로그램 소개 자료가 아니라 실습 진행 화면입니다. 각 슬라이드에서 강사는 먼저 직접 입력하고, 수강생이 같은 조작을 끝낸 뒤 다음 장으로 이동합니다.\n\n${titles.map((t,i)=>{const no=i+1;const module=slides[i].match(/data-module="([^"]+)"/)?.[1]||'setup';const action=no<=5?'강의 목표와 제출 증거를 짧게 확인합니다.':moduleActions[module];return `## ${String(no).padStart(2,'0')}. ${t}\n${action}`}).join('\n\n')}\n`;
fs.writeFileSync(path.join(deckDir,'speaker-notes.md'),notes,'utf8');

const quick=`# 강의 바로 시작\n\n1. 도입에서는 오늘 만들 순서와 제출 증거만 확인하고 완성 화면은 2분 안에 닫습니다.\n2. MODULE 01에서 OpenDART 키 발급, .env 입력, 서버와 Claude Code 실행을 화면 공유하며 직접 시연합니다.\n3. MODULE 02에서는 전체 프롬프트를 한 개씩 붙여넣고 화면 뼈대→기업 선택→기간 선택이 자라는 과정을 확인합니다.\n4. MODULE 03에서는 브라우저→Python 서버→OpenDART와 AI Provider 요청을 코드·URL·JSON으로 확인한 뒤 지표와 브리핑을 추가합니다.\n5. MODULE 04에서 GitHub와 Vercel을 실제로 연결하고 공개 URL에서 같은 조작을 재현합니다.\n\n## 화면 공유 원칙\n- 실제 API 키, .env 값, 요청 헤더는 공유하지 않습니다.\n- 강사는 키를 미리 설정한 별도 데모 환경을 사용합니다.\n- 외부 API가 실패하면 저장소 루트의 검증된 완성본과 준비된 응답 캡처로 설명을 이어가고, 수강생 작업은 보존합니다.\n`;
fs.writeFileSync(path.join(deckDir,'강의_바로시작.md'),quick,'utf8');

console.log(`Generated ${slides.length} process-first slides in ${deckDir}`);
