import type {FC} from 'react';
import {
  AiScene,
  Caption,
  CAPTIONS,
  CompareScene,
  COLORS,
  DartPromo,
  DetailScene,
  FlashCut,
  FLASHES,
  OpeningScene,
  OutroScene,
  SFX,
  SHOTS,
  StrategyScene,
  TitleCard,
  TOTAL_FRAMES,
} from './DartPromo';

const scene = (key: keyof typeof SHOTS, label: string, component: FC) => ({
  id: key,
  label,
  from: SHOTS[key].from,
  duration: SHOTS[key].duration,
  component: component as FC<Record<string, unknown>>,
  props: {},
  schema: [],
});

const title = (key: keyof typeof SHOTS, label: string, text: string, sub: string) => ({
  id: key,
  label,
  from: SHOTS[key].from,
  duration: SHOTS[key].duration,
  component: TitleCard as FC<Record<string, unknown>>,
  props: {text, sub, duration: SHOTS[key].duration},
  schema: [
    {type: 'textarea', key: 'text', label: '문구 (*단어* = 강조)', default: text},
    {type: 'text', key: 'sub', label: '영문 보조 문구', default: sub},
  ],
  durationProp: 'duration',
  cardId: 'title-card',
  cardName: 'Ink Press 제목 카드',
  accent: COLORS.teal,
});

export const WORKBENCH = {
  name: 'DART HR Briefing · Ink Press promo',
  fps: 30,
  width: 1920,
  height: 1080,
  total: TOTAL_FRAMES,
  background: COLORS.paper,
  shots: [
    scene('opening', 'S1 브랜드 → 실제 서비스', OpeningScene),
    title('title1', 'T1 같은 기준의 비교', '기업을 찾는 시간에서, *비교하는* 시간으로.', 'SEARCH ONCE · COMPARE ON THE SAME BASIS'),
    scene('compare', 'S3 기업 선택 → Overview', CompareScene),
    scene('detail', 'S4 핵심 재무지표 비교', DetailScene),
    title('title2', 'T2 수치 이상의 판단지원', '수치만 *보여주지* 않습니다.', 'FACTS · LIMITS · NEXT QUESTIONS'),
    scene('strategy', 'S6 Strategy Brief → 근거', StrategyScene),
    title('title3', 'T3 AI와 근거', '질문은 AI에게, 판단은 *근거와* 함께.', 'AI BRIEFING WITH POLICY GUARDS'),
    scene('ai', 'S8 AI 질문 → 정책 게이트', AiScene),
    title('title4', 'T4 더 나은 HR 질문', '같은 기준. 확인 가능한 출처. 더 나은 *HR_질문.*', 'FROM DISCLOSURE TO DECISION-READY QUESTIONS'),
    scene('outro', 'S10 제품 몽타주 → 공개 URL', OutroScene),
  ],
  transitions: FLASHES.map((at, index) => ({
    id: `flash-${index + 1}`,
    label: `민트 플래시 전환 @${at}f`,
    from: at - 5,
    duration: 10,
    component: FlashCut as FC<Record<string, unknown>>,
    props: {duration: 10},
    schema: [],
    durationProp: 'duration',
    cardId: 'flash-cut',
    cardName: '민트 플래시 전환',
  })),
  captions: CAPTIONS.map((caption, index) => ({
    id: `caption-${index + 1}`,
    label: caption.text,
    from: caption.from,
    duration: caption.duration,
    component: Caption as FC<Record<string, unknown>>,
    props: {text: caption.text, duration: caption.duration},
    schema: [{type: 'text', key: 'text', label: '설명 자막', default: caption.text}],
    durationProp: 'duration',
    cardId: 'caption',
    cardName: '제품 설명 자막',
  })),
  sfx: SFX.map((item) => ({
    from: item.from,
    duration: item.duration,
    src: `audio/${item.src}`,
    volume: item.volume,
  })),
  order: ['transitions', 'captions', 'overlays'] as const,
  original: DartPromo as FC<Record<string, unknown>>,
};
